name: bittrans-inference

log_configs:
  comet: False
  pandas_df: False
  wandb: False
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here

load_configs:
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here
  experiment_load_name: !!null
  experiment_load_key: !!null
  manual_load_ckpt: !!null
  local_load: True

experiment_configs:
  seed: 0
  dataset_name: ["20ng", "mr", "R8", "R52", "ohsumed", "cola", "stsb", "rte", "mrpc"]
  bert_pre_model: ["roberta-base", "bert-base-uncased"]
  device: "cuda:3"
  checkpoint_dir: !!null
  log_ckpt: False
  save_ckpt: False
  save_logits: False
  report_time: False

model_configs: 
  max_length: 128
  quantize_bert: True
  quantize_embeddings: True
  quantize_attention: True
  num_bits_act: 8.0
  num_states: 2
  adj_type: "full"
  linear_backend: "fp32"
  embedding_backend: "fp32"
  attn_backend: "fp32"

parameters: 
  batch_size: 32
  bert_quant_type: "QAT"