name: bittransgnn-inference

log_configs:
  comet: False
  pandas_df: False
  wandb: False
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here

load_configs:
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here
  experiment_load_name: !!null
  experiment_load_key: !!null
  manual_load_ckpt: !!null
  local_load: True

experiment_configs:
  seed: 0
  inference_type: "transductive"
  dataset_name: "cola"
  bert_pre_model: "bert-base-uncased"
  device: "cuda:1"
  checkpoint_dir: !!null
  log_ckpt: False
  save_ckpt: False
  save_logits: True
  report_time: False

model_configs: 
  max_length: 128
  quantize_bert: True
  quantize_embeddings: True
  quantize_attention: True
  quantize_gcn: False
  num_bits_act: 8.0
  num_states: 5
  gcn_num_states: 2
  adj_type: "full"
  linear_backend: "fp32"
  embedding_backend: "fp32"
  attn_backend: "fp32"

parameters: 
  gcn_layers: 2
  batch_size: 32
  lmbd: 0.55
  bert_quant_type: "PTQ"
  joint_training: True
  graph_hidden_size: 256
  dropout: 0.5