sweep_agent: comet
algorithm: grid
spec: 
  metric: best_val_acc #changes based on the dataset
  objective: maximize
#for wandb, use the following instead of algorithm and spec:
#method: grid
#metric:
# name: best_val_acc #changes based on the dataset
# goal: maximize

log_configs:
  comet: True
  pandas_df: False
  wandb: False
  project_name: bittransgnn-train
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here

load_configs:
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here
  experiment_load_name: !!null
  experiment_load_key: !!null
  manual_load_ckpt: !!null
  local_load: True

experiment_configs:
  seed: 0
  inference_type: "transductive"
  dataset_name: "rte"
  bert_pre_model: "bert-base-uncased"
  device: "cuda:2"
  log_ckpt: False
  save_ckpt: True
  save_logits: False
  report_time: False
  checkpoint_dir: !!null
  nb_epochs: 100
  patience: 10
  eval_test: True
  eval_test_every_n_epochs: 1

model_configs: 
  max_length: 128
  quantize_bert: True
  quantize_embeddings: True
  quantize_attention: True
  quantize_gcn: False
  num_bits_act: 8.0
  num_states: 3
  gcn_num_states: 2
  adj_type: "full"

parameters: 
  gcn_layers: 2
  bert_lr: 0.00001
  gcn_lr: 0.001
  batch_size: 32
  lmbd: 0.9
  bert_quant_type: "PTQ"
  joint_training: True
  graph_hidden_size: 256
  dropout: 0.5