name: bittransgnn-direct-seperation

log_configs:
  comet: True
  pandas_df: True
  wandb: False
  project_name: bittransgnn-direct-seperation
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here

load_configs:
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here
  experiment_load_name: !!null
  experiment_load_key: !!null
  manual_load_ckpt: !!null
  local_load: True

experiment_configs:
  seed: 0
  inference_type: "transductive"
  dataset_name: "mrpc"
  bert_pre_model: "roberta-base"
  device: "cuda:0"
  checkpoint_dir: !!null
  log_ckpt: False
  save_ckpt: False
  report_time: False
  workspace: !!null #you should enter the name of your Comet workspace here
  api_key: !!null #you should enter the api_key of your Comet account here

model_configs: 
  max_length: 128
  quantize_bert: True
  quantize_gcn: False
  quantize_embeddings: False
  num_bits_act: 8.0
  num_states: 5

parameters: 
  batch_size: 32
  bert_quant_type: "PTQ"
  joint_training: True
  #lmbd: 0.55
  lmbd: -1